import React, { useState } from 'react';
import useTransformerStore from '../store/useTransformerStore.js';

function generatePyTorchCode(config) {
  const { d_model, n_heads, d_ff, n_layers, max_seq } = config;
  const d_head = Math.floor(d_model / n_heads);

  return `"""
LLMBlock export — generated by LLMBlock Studio
Architecture: ${n_layers}-layer GPT-style transformer
  d_model  = ${d_model}
  n_heads  = ${n_heads}  (d_head = ${d_head})
  d_ff     = ${d_ff}
  n_layers = ${n_layers}
  max_seq  = ${max_seq}
"""

import torch
import torch.nn as nn
import math


class MultiHeadAttention(nn.Module):
    def __init__(self, d_model: int, n_heads: int):
        super().__init__()
        assert d_model % n_heads == 0
        self.n_heads = n_heads
        self.d_head  = d_model // n_heads
        self.Wq = nn.Linear(d_model, d_model, bias=False)
        self.Wk = nn.Linear(d_model, d_model, bias=False)
        self.Wv = nn.Linear(d_model, d_model, bias=False)
        self.Wo = nn.Linear(d_model, d_model, bias=False)

    def forward(self, x):
        B, T, C = x.shape
        H, Dh   = self.n_heads, self.d_head

        Q = self.Wq(x).view(B, T, H, Dh).transpose(1, 2)  # (B, H, T, Dh)
        K = self.Wk(x).view(B, T, H, Dh).transpose(1, 2)
        V = self.Wv(x).view(B, T, H, Dh).transpose(1, 2)

        scale  = math.sqrt(Dh)
        scores = (Q @ K.transpose(-2, -1)) / scale          # (B, H, T, T)
        attn   = torch.softmax(scores, dim=-1)
        out    = attn @ V                                     # (B, H, T, Dh)
        out    = out.transpose(1, 2).contiguous().view(B, T, C)
        return self.Wo(out), attn


class FeedForward(nn.Module):
    def __init__(self, d_model: int, d_ff: int):
        super().__init__()
        self.W1 = nn.Linear(d_model, d_ff)
        self.W2 = nn.Linear(d_ff, d_model)

    def forward(self, x):
        return self.W2(torch.nn.functional.gelu(self.W1(x)))


class TransformerBlock(nn.Module):
    def __init__(self, d_model: int, n_heads: int, d_ff: int):
        super().__init__()
        self.ln1  = nn.LayerNorm(d_model)
        self.attn = MultiHeadAttention(d_model, n_heads)
        self.ln2  = nn.LayerNorm(d_model)
        self.ffn  = FeedForward(d_model, d_ff)

    def forward(self, x):
        attn_out, attn_weights = self.attn(self.ln1(x))
        x = x + attn_out           # residual connection
        x = x + self.ffn(self.ln2(x))
        return x, attn_weights


class MiniGPT(nn.Module):
    """
    A minimal GPT-style decoder-only transformer.
    Matches the architecture shown in LLMBlock Studio.
    """
    def __init__(
        self,
        vocab_size: int = 50257,
        d_model: int    = ${d_model},
        n_heads: int    = ${n_heads},
        d_ff: int       = ${d_ff},
        n_layers: int   = ${n_layers},
        max_seq: int    = ${max_seq},
    ):
        super().__init__()
        self.embed    = nn.Embedding(vocab_size, d_model)
        self.pos_enc  = nn.Embedding(max_seq, d_model)
        self.blocks   = nn.ModuleList([
            TransformerBlock(d_model, n_heads, d_ff)
            for _ in range(n_layers)
        ])
        self.ln_final = nn.LayerNorm(d_model)
        self.head     = nn.Linear(d_model, vocab_size, bias=True)

    def forward(self, token_ids: torch.Tensor):
        B, T = token_ids.shape
        positions = torch.arange(T, device=token_ids.device).unsqueeze(0)

        x = self.embed(token_ids) + self.pos_enc(positions)

        all_attn = []
        for block in self.blocks:
            x, attn = block(x)
            all_attn.append(attn)

        x      = self.ln_final(x)
        logits = self.head(x)          # (B, T, vocab_size)
        return logits, all_attn


# ── Instantiate ────────────────────────────────────────────────────────────────
model = MiniGPT()
print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

# ── Minimal training loop ──────────────────────────────────────────────────────
# Replace with your dataset loader
def train(model, tokens, n_epochs=10, lr=3e-4):
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    model.train()
    for epoch in range(n_epochs):
        x = tokens[:, :-1]           # input  (B, T-1)
        y = tokens[:, 1:]            # target (B, T-1)  — next-token prediction
        logits, _ = model(x)
        loss = torch.nn.functional.cross_entropy(
            logits.reshape(-1, logits.size(-1)),
            y.reshape(-1),
        )
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"Epoch {epoch+1}: loss = {loss.item():.4f}")
`;
}

function generateHFConfig(config) {
  const { d_model, n_heads, d_ff, n_layers, max_seq } = config;
  return JSON.stringify({
    architectures: ['GPT2LMHeadModel'],
    model_type: 'gpt2',
    hidden_size: d_model,
    num_attention_heads: n_heads,
    num_hidden_layers: n_layers,
    intermediate_size: d_ff,
    max_position_embeddings: max_seq,
    vocab_size: 50257,
    activation_function: 'gelu',
    resid_pdrop: 0.1,
    embd_pdrop: 0.1,
    attn_pdrop: 0.1,
    layer_norm_epsilon: 1e-5,
  }, null, 2);
}

export default function PythonExportPanel() {
  const { modelConfig, paramCount } = useTransformerStore();
  const [tab, setTab] = useState('pytorch');
  const [copied, setCopied] = useState(false);

  const code = tab === 'pytorch'
    ? generatePyTorchCode(modelConfig)
    : generateHFConfig(modelConfig);

  const copy = () => {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  function fmtParams(n) {
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M';
    if (n >= 1_000) return (n / 1_000).toFixed(1) + 'K';
    return String(n);
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>

      {/* Header */}
      <div style={{ padding: '14px 14px 10px', borderBottom: '1px solid #1e293b' }}>
        <div style={{ fontSize: 13, fontWeight: 800, color: '#f1f5f9', marginBottom: 4 }}>
          🐍 Export to Python
        </div>
        <div style={{ fontSize: 11, color: '#64748b', lineHeight: 1.5 }}>
          Get runnable PyTorch code matching your current architecture.
          Paste into a notebook and train on your own data.
        </div>
      </div>

      {/* Arch summary */}
      <div style={{ display: 'flex', gap: 8, padding: '10px 14px', borderBottom: '1px solid #1e293b' }}>
        {[
          ['d_model', modelConfig.d_model],
          ['n_heads', modelConfig.n_heads],
          ['n_layers', modelConfig.n_layers],
          ['d_ff', modelConfig.d_ff],
          ['Params', fmtParams(paramCount)],
        ].map(([k, v]) => (
          <div key={k} style={{ flex: 1, background: '#1e293b', borderRadius: 6, padding: '5px 8px', textAlign: 'center' }}>
            <div style={{ fontSize: 12, fontWeight: 800, color: '#6366f1' }}>{v}</div>
            <div style={{ fontSize: 8, color: '#475569', marginTop: 1 }}>{k}</div>
          </div>
        ))}
      </div>

      {/* Tab bar */}
      <div style={{ display: 'flex', borderBottom: '1px solid #1e293b' }}>
        {[
          { id: 'pytorch', label: '🔥 PyTorch' },
          { id: 'hf', label: '🤗 HF Config' },
        ].map(t => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            style={{
              flex: 1, padding: '8px 4px', border: 'none',
              borderBottom: tab === t.id ? '2px solid #6366f1' : '2px solid transparent',
              background: 'none', cursor: 'pointer', fontSize: 11,
              color: tab === t.id ? '#818cf8' : '#475569',
              fontWeight: tab === t.id ? 700 : 400,
            }}
          >
            {t.label}
          </button>
        ))}
        <button
          onClick={copy}
          style={{
            padding: '8px 14px', border: 'none', borderBottom: '2px solid transparent',
            background: 'none', cursor: 'pointer', fontSize: 11,
            color: copied ? '#10b981' : '#64748b',
          }}
        >
          {copied ? '✓ Copied!' : '⎘ Copy'}
        </button>
      </div>

      {/* Code block */}
      <div style={{ flex: 1, overflow: 'auto' }}>
        <pre style={{
          margin: 0, padding: '12px 14px',
          fontFamily: 'ui-monospace, monospace', fontSize: 10,
          lineHeight: 1.6, color: '#cbd5e1',
          background: 'transparent', whiteSpace: 'pre',
        }}>
          {code}
        </pre>
      </div>

      {/* Footer tips */}
      <div style={{
        padding: '10px 14px', borderTop: '1px solid #1e293b',
        fontSize: 10, color: '#334155', lineHeight: 1.5,
      }}>
        💡 Change the architecture in <b style={{ color: '#6366f1' }}>⚙️</b> above — the code updates automatically.
        Install deps: <code style={{ color: '#a78bfa' }}>pip install torch</code>
      </div>
    </div>
  );
}
